## Numpy-Numerical python. It keeps homogeneous data
## 1. ndarray ( N dimensional array) and its Attributes


## 1.1.ndarray

In [ ]:
import numpy as np



# 1d array creating and checking

arr1 = np.array([1,2,3,4,5])

print(type(arr1))
print(arr1.ndim)      #Attribute 1. ndim



# 2 d array

arr2 = np.array([[1,2,3,4],    #row1
                [4,5,6,7]])   #row2

print(arr2.ndim)



# 3 d array  - Multiple 2d array in  1d array

arr3 = np.array([
          [[ 1,2,4],           #1st floor
           [ 3,4,5]],

           [[2,4,5],            #2nd floor
            [3,4,5]],

            [[2,4,5],            #3rd floor
            [3,4,9]]

])

print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


## 2. Array Attributes

In [ ]:



#1.ndim
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#2.shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#3.data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#4.size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 4)
(3, 2, 3)
int64
int64
int64
5
8
18


# 3. nd array data type

In [ ]:
arr = np.array([1,2,3,4])
print(arr.dtype)


# upcasting into float
arr = np.array([1.3,2.5,3,5.5])
print(arr.dtype)

#upcasting into string
arr = np.array ([1,2,3.2,"hello"])
print(arr.dtype)

int64
float64
<U32


In [ ]:
#Selecting datatype

arr = np.array([1,2,300],dtype = np.int32)
print(arr.dtype)



int32


In [ ]:
arr =arr.astype(np.int16)
print(arr.dtype)

int16


## 4.nd array creation from existing data

In [ ]:
#list
#1.from homogeneous list
lst = [10,20,30,40.0]

arr = np.array(lst,dtype = np.int32)

print(arr)
print(type(arr))
print(arr.dtype)

#2.from non homogeneous list

mixed_list = [10,True,'hello']  #But not possible to keep another list i9n one list,for that execution i have to keep homogeneous

arr = np.array(mixed_list)

print(arr)
print(type(arr))
print(arr.dtype)

#3.from 2d list

matrix = [[1,2,3,4],
          [4,5,6,7]]
arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)




[10 20 30 40]
<class 'numpy.ndarray'>
int32
['10' 'True' 'hello']
<class 'numpy.ndarray'>
<U21
[[1 2 3 4]
 [4 5 6 7]]
<class 'numpy.ndarray'>
int64
(2, 4)
2


In [ ]:
#tuple

tpl = (1,2,3)
arr = np.array(tpl,dtype = np.int16)
arr = arr.astype(np.int32)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int32
(3,)
1


In [ ]:
#set

st = {1,2,3}
arr = np.array([*st])  #was facing issue on arr= np.array(list(st))
print(arr.dtype)
#arr = arr.astype(np.int32)

print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)

int64
[1 2 3]
<class 'numpy.ndarray'>
(3,)
1


In [ ]:
#dictionary

dc ={'a':10,'b':20,'c':30}

keys = dc.keys()
values = dc.values()
items = dc.items()

print(keys,values,items)


#keys to ndarray

arr = np.array([*keys])  #because of string type change not executed
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


#values to ndarray

arr = np.array([*values],dtype = np.int32)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

#items to ndarray

arr = np.array([*items])
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)




dict_keys(['a', 'b', 'c']) dict_values([10, 20, 30]) dict_items([('a', 10), ('b', 20), ('c', 30)])
['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3
<class 'numpy.ndarray'>
int32
(3,)
1
3
[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


##  5.ndarray generation with random values

In [ ]:
#np.random.rand(shape)

arr = np.random.rand(2,3)  #0->1 diistributed

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


#np.random.randint(strat,end,shape)

arr = np.random.randint(1,10,(2,2,2))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

#np.random.uniform(strat,end,shape) -float

arr = np.random.uniform(50,100,(3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[0.58714714 0.35718052 0.32842622]
 [0.60169094 0.72427312 0.96585933]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6
[[[2 2]
  [9 9]]

 [[1 2]
  [5 2]]]
<class 'numpy.ndarray'>
int64
(2, 2, 2)
3
8
[[74.32075122 78.52229428 57.30402851 61.57420145]
 [82.19169759 53.63482738 95.66003374 55.37759473]
 [90.55998385 99.4733227  71.96456149 53.28060171]]
<class 'numpy.ndarray'>
float64
(3, 4)
2
12


## 6.ndarray creation from range

In [ ]:
#np.arange(first,end,step)  -> similliar to range function

arr = np.arange(1,10,1)
mat = arr.reshape(3,3)       #->reshape
print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [ ]:
#linspace
#np.linspace(start , end , how many)

arr = np.linspace(1,10,12)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)



[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]
<class 'numpy.ndarray'>
float64
(12,)
1
12


In [ ]:
#np.logspace(start, end (included),koita)
arr = np.logspace(0,4,5)
arr1 = np.logspace(0,4,6,base = 2)
print(arr)
print(arr1)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


## 7.ndarray indexing and slicing

In [ ]:
#indexing


print(arr2)

arr2[0][2] = 0
print(arr2)

[[  1   2 100   4]
 [  4   5   6   7]]
[[1 2 0 4]
 [4 5 6 7]]


## 8.ndarray Copy Advanced Indexing and Iteration