### 4.Numpy logical function

In [ ]:
#comparison
import numpy as np
x = np.array([10,8,16,100])
y = np.array([2,3,4,5])

greater_than = x>y
print(greater_than)
equal = x ==y

print(equal)

#all () - > all true or not
#any () - > atleast one element true or not

print(np.all(greater_than))
print(np.any(equal))

[ True  True  True  True]
[False False False False]
True
False


### 5.ndarray sortiong

In [ ]:
#inplace_sorting

x = np.array([10,8,16,100])
z = x.copy()

print(z)


z.sort()
print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [ ]:
#copy_sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [ ]:
#2 d array sorting

mat = np.array([[10,3,5],[8,4,9]])

#horizontal_axis = 1

hor_sort = np.sort(mat,axis = 1)
print(hor_sort)

ver_sort = np.sort(mat,axis = 0)
print(ver_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


### 6.ndarray searching

In [11]:
x = np.array([10,8,16,100])
print(x)

[ 10   8  16 100]


In [12]:
#np.where(condition, x,y) if true x, otherwise replace with y

index = np.where(x==8)     #return index
print(index)

index = np.where(x>8,x,0)    #return array
print(index)

(array([1]),)
[ 10   0  16 100]


In [13]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [14]:
index = np.where(mat>8) #return index
print(index)

(array([0, 1]), array([0, 2]))


In [17]:
x = np.array([10,100,8,16,100])

maximum_value_idx= np.argmax(x)
minimum_value_idx = np.argmin(x)
print(maximum_value_idx)
print(minimum_value_idx)

1
2


### 7.ndarray Counting

In [18]:
a = np.random.randint(1,100,size=(100,))
print (a)

[94 69 93 67 47 61 74 53  3 97  2 79 96 72 45 39  1 17 41 27 67 57 88 65
 75  7 36 55 55 69 31  8 70 27 54 15 77  3  4 19 68 17 70 44 44 73 42 40
 35 79 22 71 28 44 35 19 88  1 26 43 84 39 37 11  2 36 15 96 60 49 61 79
 60 68 18 12 35  2 41 80 28 59 74 57 81 73 55 84 45 49  4 66 16 74 56 50
 14 49 64  5]


In [19]:
#count_nonzero(condition)

value_great_than = np.count_nonzero(a<30)
print(value_great_than)

29


In [24]:
unique_value,count= np.unique(a,return_counts = True)
print(unique_value)
print(count)

[ 1  2  3  4  5  7  8 11 12 14 15 16 17 18 19 22 26 27 28 31 35 36 37 39
 40 41 42 43 44 45 47 49 50 53 54 55 56 57 59 60 61 64 65 66 67 68 69 70
 71 72 73 74 75 77 79 80 81 84 88 93 94 96 97]
[2 3 2 2 1 1 1 1 1 1 2 1 2 1 2 1 1 2 2 1 3 2 1 2 1 2 1 1 3 2 1 3 1 1 1 3 1
 2 1 2 2 1 1 1 2 2 2 2 1 1 2 3 1 1 3 1 1 2 2 1 1 2 1]


### 8.statistical function

In [25]:
#data load

data = np.genfromtxt('student_scores.csv' ,delimiter=',',skip_header=1)

print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [28]:
# statistics
math_marks = data[::,:1]
print(math_marks.T)


max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [29]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


### 10.Linear algebra


In [30]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)


# trace
print(np.trace(B))


[[ 58  64]
 [139 154]]
17


In [31]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

0.0
2


In [32]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
