### 7.ndarray  indexing and slicing

In [2]:
##indexing
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3],
                 [4,5,6]])

arr1[2] = 30
print(arr1)


arr2[1][1] = 100
print(arr2)

[ 1  2 30  4  5  6]
[[  1   2   3]
 [  4 100   6]]


In [3]:
#slicing


#1d  = arr[start:end:step]

arr1_mod = arr1[::2]
print(arr1_mod)



[ 1 30  5]


In [4]:
# 2d slicing
# arr[row_start : row_end : step , column_start: column_end : end]

arr2 = np.array([[1,2,3],
                 [4,5,6]])


#getting a row
#suppose i want extract first row
arr2_row = arr2[:1:,::]
print(arr2_row)

#getting a column
#suppose i want extract middle column

arr2_col = arr2[ ::,1:2:]
print(arr2_col)

[[1 2 3]]
[[2]
 [5]]


### 8.ndarray copy advanced indexing and iteration


In [5]:
#copy


a = np.array([1, 2, 3])
b = a.copy()   # real copy

b[0] = 100
print(a,b)  # [1, 2, 3]  ← original unchanged

[1 2 3] [100   2   3]


In [6]:
# Advance indexing
#1d array
lst = np.array([1,2,3,4,5,6])

values = lst[[3,1]]

print(values)

[4 2]


In [7]:
#2d array

arr2 = np.array([[1,2,3],
                 [4,5,6]])
# 2,6 print
print(arr2[[0,1],[1,2]])

[2 6]


In [8]:
#iteration

arr =np.array([[1,2,3,4],[5,6,7,8]])

for i in arr:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [9]:
#or
for i in arr:
    for j in i:
      print(j)

1
2
3
4
5
6
7
8


In [10]:
#or
for i in np.nditer(arr):
  print(i)


1
2
3
4
5
6
7
8


### 1.ndarray Manipulation -1

In [11]:
arr = np.random.randint(1,100,size = (10,5))  #sample -10,feature - 5
arr.shape

(10, 5)

In [16]:
b = arr.reshape(5,10)
b.shape
b.ndim
b

array([[45, 25, 37, 19, 24, 76, 21, 74,  7, 78],
       [50, 84,  8, 82, 84, 25, 64, 85, 48, 98],
       [33,  8, 15, 57, 66,  9, 73, 46, 98, 45],
       [87, 63, 47, 56, 23, 20, 80, 35, 56, 20],
       [46, 11, 43, 94, 11,  3, 40, 64,  3, 72]])

In [20]:
#row_wise
flatten = b.flatten()
print(flatten.ndim)
flatten




1


array([45, 25, 37, 19, 24, 76, 21, 74,  7, 78, 50, 84,  8, 82, 84, 25, 64,
       85, 48, 98, 33,  8, 15, 57, 66,  9, 73, 46, 98, 45, 87, 63, 47, 56,
       23, 20, 80, 35, 56, 20, 46, 11, 43, 94, 11,  3, 40, 64,  3, 72])

In [21]:
#column_wise
column_wise_flattening = np.ravel(b,order = 'F')  #'C' for column
print(column_wise_flattening)

[45 50 33 87 46 25 84  8 63 11 37  8 15 47 43 19 82 57 56 94 24 84 66 23
 11 76 25  9 20  3 21 64 73 80 40 74 85 46 35 64  7 48 98 56  3 78 98 45
 20 72]


In [24]:
#concatenate
a = np.random.randint(1,10,size =(2,3))
b = np.random.randint (20,30,size =(2,3))
print(a,b)

[[6 6 4]
 [8 4 5]] [[24 25 24]
 [22 21 22]]


In [26]:
con_row = np.concatenate((a,b),axis = 0)  # for row wise concatenate axis = 0
print(con_row)

con_col = np.concatenate((a,b),axis = 1)    # for column wise concatenate axis = 1
print(con_col)

[[ 6  6  4]
 [ 8  4  5]
 [24 25 24]
 [22 21 22]]
[[ 6  6  4 24 25 24]
 [ 8  4  5 22 21 22]]


In [32]:
#error
#in row wise concatenate , column have to be same
#in column wise concatenate, row have to be same
x  = np.random.randint(1,10, size =(2,3))
y  = np.random.randint(1,10, size =(1,3))

r = np.concatenate((x,y),axis = 1)
print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

### 2.ndarray Manipulation - 2

In [36]:
#Transpose
mat = np.array([[10,20,30],
              [30,20,60]])

Transpose = mat.T
print(Transpose)

[[10 30]
 [20 20]
 [30 60]]


In [37]:
#array split

a = np.random.randint(1,10,size = (10,))

splitted_array = np.array_split(a,3)

print(splitted_array)

[array([6, 6, 4, 6]), array([5, 7, 2]), array([2, 7, 7])]


### 3.ndarray Arithmetic Operators and Mathematical function

In [41]:
#faster for vectoraization

x  =np.array([10,20,30,40])
y  = np.array([2, 3, 4, 5])

add = x + y
sub = x - y
mul = x * y
div = x / y
print(add ,sub ,mul ,div)

[12 23 34 45] [ 8 17 26 35] [ 20  60 120 200] [5.         6.66666667 7.5        8.        ]


In [44]:
#mathematical function

#trigonometry
sin_val = np.sin(x)
print(sin_val)

deg_con = np.rad2deg(x)
print(deg_con)

#deg2rad

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


In [48]:
#log
base_10_log_val = np.log10(x)
print(base_10_log_val)

two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt = np.sqrt(x)
print(sqrt)

[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]
[3.16227766 4.47213595 5.47722558 6.32455532]


In [54]:
#different
s = np.sum(x)
print(s)

cuml = np.cumsum(x)
print(cuml)

100
[ 10  30  60 100]
