
## 1.ndarray(N dimensional array) and its Attributes


## 1.1.nd array

In [ ]:
#1d array creating and checking
import numpy as np

arr1= np.array([1,2,3,4])
print(arr1)
print(arr1.ndim)


print("")
#2d array

arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)
print(arr2.ndim)

print("")
#3d array

arr3 = np.array([
    [[1,2,3],
    [1,3,4]],


    [[1,2,3],
    [1,2,3]],


    [[6,7,8],
     [2,4,5]]

])
print(arr3)
print(arr3.ndim)

[1 2 3 4]
1

[[1 2 3 4]
 [1 2 3 4]]
2

[[[1 2 3]
  [1 3 4]]

 [[1 2 3]
  [1 2 3]]

 [[6 7 8]
  [2 4 5]]]
3


## 2.Array Atribute

In [ ]:
#1.ndim
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

print("")
#2.shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

print("")
#3.datatype
print(arr1.dtype)
print(arr2.dtype)
print(arr3.shape)

print("")
#4.size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3

(4,)
(2, 4)
(3, 2, 3)

int64
int64
(3, 2, 3)

4
8
18


## 3.nd array data type

In [ ]:
arr = np.array([1,2,3,4])
print(arr.dtype)

#upcasting into float
arr = np.array([1,2,3,4.5])
print(arr.dtype)

#upcasting into string
arr = np.array([1,2,3.4,4,"hello"])
print(arr.dtype)

print("")
#selecting data type
arr = np.array([1,2,3,3.5],dtype = np.int32)
print(arr.dtype)

print("")
arr = arr.astype(np.int16)
print(arr.dtype)

int64
float64
<U32

int32

int16


## 4.nd array creation from existing data

In [ ]:
#list
#1.from homogeneous list
lst=[1,2,3,4,5]
arr = np.array(lst,dtype = np.int32)

print(arr)
print(type(arr))
print(arr.dtype)

print("")
#2.from non homogeneous list
mixed_list = [10,True,"hello"]
arr = np.array(mixed_list)

print(arr)
print(type(arr))
print(arr.dtype)


print("")
#3.from 2d list
matrix = [[1,2,3],
          [2,3,4]]
arr = np.array(matrix)


print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32

['10' 'True' 'hello']
<class 'numpy.ndarray'>
<U21

[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>
int64


In [ ]:
#tuple
tpl = (1,2,3)
arr = np.array(tpl)
arr = arr.astype(np.int32)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[1 2 3]
<class 'numpy.ndarray'>
int32
1
(3,)


In [ ]:
#set
st ={1,2,3}
arr = np.array([*st])
print(arr.dtype)

arr = arr.astype(np.int32)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int64
<class 'numpy.ndarray'>
int32
(3,)
1


In [ ]:
#dictionary

dc = {'a':10,'b':20,'c':30}

keys = dc.keys()
values = dc.values()
items = dc.items()

print(keys,values,items)


print("")
#keys to ndarray

arr = np.array([*keys])
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)



print("")
#values to nd array

arr = np.array([*values])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)


print("")
#items to ndarray

arr = np.array([*items])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)

dict_keys(['a', 'b', 'c']) dict_values([10, 20, 30]) dict_items([('a', 10), ('b', 20), ('c', 30)])

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
1
(3,)
3

[10 20 30]
<class 'numpy.ndarray'>
1
int64
(3,)
3

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
2
<U21
(3, 2)
6


## 5.nd generation with random values

In [ ]:
#np.random.rand(shape)

arr = np.random.rand(2,3)   #0->1 distributed

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.size)

[[0.65593327 0.90673087 0.46088765]
 [0.7844948  0.75791317 0.41023159]]
<class 'numpy.ndarray'>
float64
2
6


In [ ]:
#np.random.randint(start,end,shape)

arr = np.random.randint(1,10,(2,2,2))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[7 2]
  [7 7]]

 [[8 3]
  [5 3]]]
<class 'numpy.ndarray'>
int64
(2, 2, 2)
3
8


In [ ]:
#np.random.uniform(start,end,shape) - float

arr = np.random.uniform(50,100,(3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[75.14961492 85.10765192 95.06911108 55.34857677]
 [57.13368394 69.5751872  68.35226309 74.14946432]
 [98.98849642 66.77320804 59.8350452  81.44297995]]
<class 'numpy.ndarray'>
float64
2
(3, 4)
12


##6.nd array creation from built-in paceholder

In [ ]:
zeros_matrix = np.zeros((2,3,4))
print(zeros_matrix)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
ones_matrix = np.ones((2,3))
print(ones_matrix)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
seven_matrix = np.full((2,2),7)
print(seven_matrix)

[[7 7]
 [7 7]]


In [ ]:
empty_arr = np.empty((2,3))
print(empty_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


##7.nd array creation from range

In [ ]:
#np.arange(first(included),end,step)  -> similliar to range function

arr = np.arange(1,10,1)
mat = arr.reshape(3,3)

print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [ ]:
#linspace
#np.linspace(start,end,how many)

arr = np.linspace(1,10,12)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]
<class 'numpy.ndarray'>
float64
(12,)
1
12


In [ ]:
#np.logspace(start,end(included),how many)

arr = np.logspace(0,4,5)
arr1 = np.logspace(1,4,6,base = 2)
print(arr)
print(arr1)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
[ 2.          3.03143313  4.59479342  6.96440451 10.55606329 16.        ]


## 8.ndarray indexing and slicing

In [ ]:
#indexing

#1d
arr1 = np.array([1,2,3,4,5,6])

#2d
arr2 = np.array([[1,2,3],
                [4,5,6]])

arr1[2]= 30
print(arr1)


arr2[1][1] = 100
print(arr2)

[ 1  2 30  4  5  6]
[[ 1  2  3]
 [ 4 30  6]]


In [ ]:
#slicing

#1d = arr[start:end:step]

arr1_mod = arr1[::2]
print(arr1_mod)


print("")
#2d slicing
#arr[row start : row end :step, column_start: column_end: end]
arr2 = np.array([[1,2,3],
                [4,5,6]])

print("")
#getting a row
#suppose i want extract first row
arr2_row = arr2[:1:,::]
print(arr2_row)


print("")
#getting a column
#suppose i want extract middle column
arr2_col = arr2[::,1:2:]
print(arr2_col)

[ 1 30  5]


[[1 2 3]]

[[2]
 [5]]


## 9.ndarray copy advanced indexing and iteration

In [ ]:
#copy

a = np.array([1,2,3])
b = a.copy()    #real copy

b[0] = 100
print(a,b)

[1 2 3] [100   2   3]


In [ ]:
#Advancing indexing
#1d array
lst = np.array([1,2,3,4,5,6])
values = lst[[3,1]]
print(values)

[4 2]


In [ ]:
#2d array
arr2 = np.array([[1,2,3],
                 [4,5,6]])
#2,6 print
print(arr2[[0,1],[1,2]])

[2 6]


In [ ]:
#iteration

arr =np.array([[1,2,3,4],[5,6,7,8]])

for i in arr:
    print(i)

#or
print("")
for i in arr:
    for j in i:
      print(j)

#or
print("")
for i in arr:
    for j in i:
      print(j)

#or
print("")
for i in np.nditer(arr):
  print(i)

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8

1
2
3
4
5
6
7
8


#10.ndarray Manipulation -1

In [ ]:
  arr = np.random.randint(1,1000,size =(10,5))      #sample -10,feature - 5
  arr.shape

  print("")
  b=arr.reshape(5,10)
  b.shape
  b

array([[111, 385, 226, 558, 192, 481, 171, 516, 890, 824],
       [627, 936, 723, 169, 937,  16, 349, 902, 401, 758],
       [461, 887, 170, 760, 932, 545, 458, 214, 402, 192],
       [959, 677, 933, 285, 774, 557, 461, 171, 175, 301],
       [870, 583, 510, 102, 143, 107, 196, 619, 502, 843]])

In [ ]:
 #row_wise
 flatten = b.flatten()
 print(flatten.ndim)
 flatten

1


array([111, 385, 226, 558, 192, 481, 171, 516, 890, 824, 627, 936, 723,
       169, 937,  16, 349, 902, 401, 758, 461, 887, 170, 760, 932, 545,
       458, 214, 402, 192, 959, 677, 933, 285, 774, 557, 461, 171, 175,
       301, 870, 583, 510, 102, 143, 107, 196, 619, 502, 843])

In [ ]:
# column wise
column_wise_flattening = np.ravel(b,order = "F")
print(column_wise_flattening)

[111 627 461 959 870 385 936 887 677 583 226 723 170 933 510 558 169 760
 285 102 192 937 932 774 143 481  16 545 557 107 171 349 458 461 196 516
 902 214 171 619 890 401 402 175 502 824 758 192 301 843]


In [ ]:
#concatenate
a = np.random.randint(1,10,size =(2,3))
b = np.random.randint (20,30,size =(2,3))
print(a,b)

[[4 5 4]
 [6 5 3]] [[22 28 26]
 [25 28 23]]


In [ ]:
con_row = np.concatenate((a,b),axis = 0)   # for row wise concatenate axis = 0
print(con_row)

[[ 4  5  4]
 [ 6  5  3]
 [22 28 26]
 [25 28 23]]


In [ ]:
con_col = np.concatenate((a,b),axis = 1)   # for column wise concatenate axis = 1
print(con_col)

[[ 4  5  4 22 28 26]
 [ 6  5  3 25 28 23]]


In [ ]:
#error
#in row wise concatenate , column have to be same
#in column wise concatenate, row have to be same
x  = np.random.randint(1,10, size =(2,3))
y  = np.random.randint(1,10, size =(1,3))

r = np.concatenate((x,y),axis = 1)
print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

## 11.ndarray Manipulation - 2

In [ ]:
#Transpose
mat = np.array([[10,20,30],
                [30,20,60]])
Transpose = mat.T
print(Transpose)

[[10 30]
 [20 20]
 [30 60]]


In [ ]:

#array split

a = np.random.randint(1,10,size = (10,))
print(a)

splitted_array = np.array_split(a,3)
print(splitted_array)

[8 3 4 6 9 3 8 9 2 2]
[array([8, 3, 4, 6]), array([9, 3, 8]), array([9, 2, 2])]


##12.ndarray Arithmetic Operators and Mathematical function

In [ ]:

#faster for vectoraization

x  =np.array([10,20,30,40])
y  = np.array([2, 3, 4, 5])

add = x + y
sub = x - y
mul = x * y
div = x / y
print(add ,sub ,mul ,div)


[12 23 34 45] [ 8 17 26 35] [ 20  60 120 200] [5.         6.66666667 7.5        8.        ]


In [ ]:

#trigonometry
sin_val = np.sin(x)
print(sin_val)

print("")
#deg2rad
deg_con = np.rad2deg(x)
print(deg_con)

[-0.54402111  0.91294525 -0.98803162  0.74511316]

[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


In [ ]:
#log
base_10_log_val = np.log10(x)
print(base_10_log_val)

two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt = np.sqrt(x)
print(sqrt)

[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]
[3.16227766 4.47213595 5.47722558 6.32455532]


In [ ]:
#different
s = np.sum(x)
print(s)

cuml = np.cumsum(x)
print(cuml)

100
[ 10  30  60 100]


#13.Numpy logical function


In [ ]:
#comparison
import numpy as np
x = np.array([10,8,16,100])
y = np.array([2,3,4,5])

greater_than = x>y
print(greater_than)
equal = x ==y

print(equal)

#all () - > all true or not
#any () - > atleast one element true or not

print(np.all(greater_than))
print(np.any(equal))

[ True  True  True  True]
[False False False False]
True
False


##14.ndarray sortiong

In [ ]:
#inplace_sorting

x = np.array([10,8,16,100])
z = x.copy()

print(z)


z.sort()
print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [ ]:
#copy_sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [ ]:

#2 d array sorting

mat = np.array([[10,3,5],[8,4,9]])

#horizontal_axis = 1

hor_sort = np.sort(mat,axis = 1)
print(hor_sort)

ver_sort = np.sort(mat,axis = 0)
print(ver_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


#15.ndarray searching

In [ ]:

x = np.array([10,8,16,100])
print(x)

print("")

#np.where(condition, x,y) if true x, otherwise replace with y

index = np.where(x==8)     #return index
print(index)

index = np.where(x>8,x,0)    #return array
print(index)




[ 10   8  16 100]

(array([1]),)
[ 10   0  16 100]


In [ ]:
print(mat)

print("")
index = np.where(mat>8) #return index
print(index)

print("")
x = np.array([10,100,8,16,100])

maximum_value_idx= np.argmax(x)
minimum_value_idx = np.argmin(x)
print(maximum_value_idx)
print(minimum_value_idx)


[[10  3  5]
 [ 8  4  9]]

(array([0, 1]), array([0, 2]))

1
2


## 16.ndarray Counting

In [ ]:
a = np.random.randint(1,100,size=(100,))
print (a)

[82  5 59 59 55 27 47 50 63 50 95  1 72 68 95 84 16 79 32 75 18  4 55 29
 16 12 76 69 71 88  5 61 45  1 84 16 28  4 54 47 73 56 85 18 82 61 34 15
 57  2 60 40 88 12 81 32 61 50 33 57 88 71 77 60 29 17 94 86 27 58 29  4
 67 71  9 51 69 96 61 58 61 12 69 29 90 87 13 56 14 48 51 84 83 69 41 32
 95 18 25 18]


In [ ]:

#count_nonzero(condition)

value_great_than = np.count_nonzero(a<30)
print(value_great_than)


31


In [ ]:
unique_value,count= np.unique(a,return_counts = True)
print(unique_value)
print(count)

[ 1  2  4  5  9 12 13 14 15 16 17 18 25 27 28 29 32 33 34 40 41 45 47 48
 50 51 54 55 56 57 58 59 60 61 63 67 68 69 71 72 73 75 76 77 79 81 82 83
 84 85 86 87 88 90 94 95 96]
[2 1 3 2 1 3 1 1 1 3 1 4 1 2 1 4 3 1 1 1 1 1 2 1 3 2 1 2 2 2 2 2 2 5 1 1 1
 4 3 1 1 1 1 1 1 1 2 1 3 1 1 1 3 1 1 3 1]


## 17.statistical function

In [ ]:
#data load

data = np.genfromtxt('student_scores.csv' ,delimiter=',',skip_header=1)

print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [ ]:
# statistics
math_marks = data[::,:1]
print(math_marks.T)


max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation
std_math_marks = np.std(math_marks)
print(std_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [ ]:

study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)


Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


## 18.Linear algebra

In [ ]:
 A= np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)


# trace
print(np.trace(B))


[[ 58  64]
 [139 154]]
17


In [ ]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)



0.0
2


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
